[book]
authors = ["Amin Jamal"]
language = "en"
src = "docs"
title = "vod-module-rs"

[build]
build-dir = "target/book"
create-missing = false

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/includeamin/vod-module-rs"
edit-url-template = "https://github.com/includeamin/vod-module-rs/edit/main/{path}"
site-url = "/vod-module-rs/"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.search]
enable = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
