[book]
authors = ["Amin Jamal"]
language = "en"
src = "docs"
title = "segmentor"

[build]
build-dir = "target/book"
create-missing = false

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/includeamin/segmentor"
edit-url-template = "https://github.com/includeamin/segmentor/edit/main/{path}"
site-url = "/segmentor/"
additional-js = ["docs/assets/js/mermaid.min.js", "docs/assets/js/mermaid-init.js"]

[output.html.search]
enable = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
